ALTER TABLE ocean_gis.gis_task
    ADD COLUMN target_crs VARCHAR(100),
    ADD COLUMN tile_profile VARCHAR(100),
    ADD COLUMN output_format VARCHAR(100);

CREATE TABLE ocean_gis.gis_processing_task_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES ocean_gis.gis_task(id),
    file_index INTEGER NOT NULL,
    original_name VARCHAR(500) NOT NULL,
    storage_key VARCHAR(1000) NOT NULL,
    output_key VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    error_message VARCHAR(1000),
    CONSTRAINT uk_gis_processing_task_file_index UNIQUE (task_id, file_index),
    CONSTRAINT ck_gis_processing_task_file_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_gis_processing_task_file_task
    ON ocean_gis.gis_processing_task_file (task_id, file_index);
